### ISSUE TITLE
Xcode Template

### ISSUE THREAD

**Issue by DnyaneshwarWagh** [CoreKit/VIPERA#2]
Hi @tib ,
   I have converted VIPERA templates for Xcode. kindly check out at [VIPER-Module-Xcode-Template](https://github.com/DnyaneshwarWagh/VIPER-Module-Xcode-Template.git). 😃

**Comment by tib** [comment]
Wow, that's amazing! Do you want to integrate the template into this repository as well? 
I'd love to have one single tool capable of installing Xcode templates too. 😄

**Comment by DnyaneshwarWagh** [comment]
Check new PR 😃

**Comment by tib** [comment]
Thank you! I'm closing this issue. 😉
